### ISSUE TITLE
Crashes whenever i try to host

### ISSUE THREAD

**Issue by BBG56789** [Snirozu/Funkin-Psych-Online#10]
### Describe your bug here.

See title
![image](https://github.com/Snirozu/Funkin-Psych-Online/assets/152926475/875bbb00-0b6f-4f2c-8189-3b01e4e79249)

### Command Prompt/Terminal logs (if existing)

```bash
had to put the image for it in describing the bug TwT
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just downloaded like 3 mods

**Comment by Snirozu** [comment]
it'll be fixed in the next version but for now, you can try playing on the latest [dev build](https://nightly.link/Snirozu/Funkin-Psych-Online/workflows/main/main)

**Comment by BBG56789** [comment]
gonna try the dev build, and if that doesn't work,  ima  just use it for the mod downloader until it gets fixed
