### ISSUE TITLE
Crashes when setting the color of the notes when online.

### ISSUE THREAD

**Issue by MikakunKun** [Snirozu/Funkin-Psych-Online#12]
### Describe your bug here.

Null Object Reference

Called from options.NotesSubState.updateNotes (options/NotesSubState.hx line 664)
Called from options.NotesSubState.new (options/NotesSubState.hx line 141)
Called from options.OptionsState.openSelectedSubstate (options/OptionsState.hx line 19)
Called from options.OptionsState.update (options/OptionsState.hx line 101)
Called from flixel.FlxState.tryUpdate (flixel/FlxState.hx line 222)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 752)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 682)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 556)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Snirozu** [comment]
works without any crashes for me
