### ISSUE TITLE
make android mobile version of fnf online

### ISSUE THREAD

**Issue by BolasBR** [Snirozu/Funkin-Psych-Online#22]
### What feature do you want to get added on the **base** engine?

I would like to tell you to make the mobile version of this game, both Android and IOS, this game is very good, and I'm sure there will be a lot more downloads after the mobile version from this version. Thanks

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment]
fuck you

**Comment by Magniill** [comment]
nuh uh uh, no mobile for ya

**Comment by mcagabe19** [comment]
well til now https://github.com/MobilePorting/Funkin-Psych-Online-Mobile/releases
