### ISSUE TITLE
Verifying a mods integrity in-game causes the gameplay to stop but the music continues playing.

### ISSUE THREAD

**Issue by Paindeluxe** [Snirozu/Funkin-Psych-Online#24]
### Describe your bug here.

While Verifying a Mods integrity if you happen to currently play a Song while it finishes you get kicked out of the Song without the Music stopping.

I have a Video recording of this in the Linux build, I did not test this on Windows or MacOS https://youtu.be/LQiNQfSGIB0 

This is unrelated to this Bug Report, but how do I get mods to work? I enabled a mod that I downloaded from the Mod downloader but it didn't work.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed nothing, this is the stock build of this Engine.

**Comment by xav07theboi** [comment]
quite weird
