### ISSUE TITLE
help idk what to do to fix the source code

### ISSUE THREAD

**Issue by Toys2313Real** [Snirozu/Funkin-Psych-Online#3]
### Describe your problem here.

it just dont work 
![image](https://github.com/Snirozu/Funkin-Psych-Online/assets/144585770/3d285804-8845-468f-9a59-a5b8565810ff)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Snirozu** [comment]
run hmm install before compiling

**Comment by Toys2313Real** [comment]
doesnt work

> run `hmm install` before compiling

**Comment by KarimAkra** [comment]
haxelib install hmm
haxelib run hmm install

**Comment by Magniill** [comment]
run `haxelib run hmm install` in your folder
