### ISSUE TITLE
Gameplay Modifiers DropDown Menu

### ISSUE THREAD

**Issue by Memelord111** [Snirozu/Funkin-Psych-Online#30]
### What feature do you want to get added on the **base** engine?

can you have it where when you press enter on gameplay modifiers it pulls out a dropdown menu below instead of the basic gameplay modifier menu.
also maybe in a later update can you add a random playback speed option to it kinda like how js engine does it.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Magniill** [comment]
i don't think the random playback speed thing will be added
