### ISSUE TITLE
Error when trying to record replay

### ISSUE THREAD

**Issue by DarkRazer1** [Snirozu/Funkin-Psych-Online#38]
### Describe your bug here.

![Capture](https://github.com/user-attachments/assets/4e78d474-1736-49b2-9b23-e2a05e967139)
(This happens with base game songs too btw)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Sky4580** [comment]
It happens when I enable "Enable Replays Recording"

**Comment by Sky4580** [comment]
[PsychEngine_2024-07-27_21'14'29.txt](https://github.com/user-attachments/files/16401912/PsychEngine_2024-07-27_21.14.29.txt)
