### ISSUE TITLE
I'm getting this error when trying to open the game

### ISSUE THREAD

**Issue by Kirll-cpu** [Snirozu/Funkin-Psych-Online#43]
### Describe your bug here.

![изображение_2024-08-09_180531168](https://github.com/user-attachments/assets/77befa1d-de4f-4390-897d-d4e806ec38ec)

### Steps to reproduce this bug.

just open the game

### Command Prompt/Terminal logs

```bash
No logs
```

### Have you modded the build?

no

### If you edited anything in this build, mention or summarize your changes.

I haven't done anything

### What is your platform?

Windows

**Comment by moxie-coder** [comment]
make sure you’re not opening the game in an directory with special characters

**Comment by Kirll-cpu** [comment]
i've checked just now, and no, i have no special characters

**Comment by Kirll-cpu** [comment]
This issue is now invalid, i've found the solution by myself
