### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by CrescentMoonbeam** [Snirozu/Funkin-Psych-Online#44]
### Describe your bug here.

I can't compile 0.7.6.

### Command Prompt/Terminal logs

```bash
source/macro/Macro.hx:13: characters 8-30 : Type not found : tea.backend.SScriptVer
source/macro/Macro.hx:14: characters 8-33 : Type not found : tea.backend.crypto.Base32
source/macro/Macro.hx:43: characters 43-53 : Type not found : SScriptVer
```

### Have you modded the build?

Yes, at Source Code level

### If you edited anything in this build, mention or summarize your changes.

I didn't make any edits

### What is your platform?

Windows

**Comment by Snirozu** [comment]
the sscript owner became a bitch ass and removed every version from the haxelib repo so you can't really do anything about it, though you can try to use a archived version of it from https://lib.haxe.org/p/SScript-Old/ (haven't tested)

**Comment by CrescentMoonbeam** [comment]
This didn't work, but I found that I had 19.0.18 installed and adjusted the .current file to use it, and now I get this:
`source/Main.hx:55: characters 42-74 : Cannot execute `git rev-parse HEAD`. fatal: not a git repository (or any of the parent directories): .git
source/Main.hx:55: characters 42-74 : ...
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here`

Does this mean anything or am I still screwed?

**Comment by Snirozu** [comment]
yeah you can't really do anything about it

**Comment by CrescentMoonbeam** [comment]
Damn, that sux. Thanks for telling me tho
