### ISSUE TITLE
HOW TO FIX THIS BRO

### ISSUE THREAD

**Issue by DavesTheBone** [Snirozu/Funkin-Psych-Online#50]
### help me plz

![Friday Night Funkin'_ Psych Online 2024_09_22 23_35_18](https://github.com/user-attachments/assets/08251b0e-5a7f-4db8-a326-1d5e98e45fc4)
![Friday Night Funkin'_ Psych Online 2024_09_22 23_35_21](https://github.com/user-attachments/assets/419a24a4-f3fa-49d8-9193-a4f8cb6bffc1)

### Steps to reproduce this bug.

idk

### Have you modded the build?

nuh uh

### If you edited anything in this build, mention or summarize your changes.

what

### What is your platform?

Windows

**Comment by Snirozu** [comment]
can you connect to [funkin.sniro.boo](https://funkin.sniro.boo) via the browser?

**Comment by DavesTheBone** [comment]
I tried, but couldn't figure out how to do it.

**Comment by NAEL2XD** [comment]
use a VPN if you can't access it (will increase your ping!)

**Comment by DavesTheBone** [comment]
Thank you! I am now able to play online successfully!
