### ISSUE TITLE
The server is not found

### ISSUE THREAD

**Issue by Keast09** [Snirozu/Funkin-Psych-Online#53]
### Describe your bug here.

I was playing fine, but suddenly when I went to change the server from "shiro" to "gettin" nothing happened. So I went back with the "shiro" server but now it's saying that it doesn't have the necessary server API. And when I go to the site to log into my account the browser says the same thing. 
![Screenshot_20240926_102411](https://github.com/user-attachments/assets/a88e10e0-a165-419f-a0d5-0fe3885a6bd9)

### Steps to reproduce this bug.

1. Online Mode 
2. Options
3. Log in or back to main menu
4. Error from API 

### Have you modded the build?

No

### What is your platform?

ANDROID

**Comment by moxie-coder** [comment]
this ain't the right repo to make this issue
