### ISSUE TITLE
shader not appearing in online

### ISSUE THREAD

**Issue by xav07theboi** [Snirozu/Funkin-Psych-Online#60]
### Describe your bug here.

i'm attempting to put a shader on the camera but it doesn't appear in psych online at all but it works in normal psych engine.

### Steps to reproduce this bug.

apply the shader to the camera hud or main camera in any way.

### Have you modded the build?

Yes, using Mods

### What is your platform?

Linux

**Comment by xav07theboi** [comment]
forgot to mention i am applying the shader mid-song

**Comment by NAEL2XD** [comment]
the fucked the shaders, take it (stay on latest) or leave it (go to old ver but never use online)
