### ISSUE TITLE
Mod downloading from Gamebanana won't work

### ISSUE THREAD

**Issue by David-Anima** [Snirozu/Funkin-Psych-Online#61]
### Describe your bug here.

Trying to download a mod from Gamebanana results in the download failing. This doesn't happen if you try to download from Google Drive or Mediafire.
![image](https://github.com/user-attachments/assets/717ea9d1-b343-4cd0-ae0f-a06339030e71)

### Steps to reproduce this bug.

1. Go to Online > Mod Downloader
2. Select a mod you want to download
3. Choose a Gamebanana download method (the one under "Files")
4. The download will fail with error "Failed to connect! (Retry #X) EOF"

### Have you modded the build?

Yes, using Mods

### What is your platform?

Windows

**Comment by Snirozu** [comment]
that's an issue with the gamebanana itself, try again a minute later for the gb server to cache the server or find another mod that hosts the mod on another file host

**Comment by Gabopogi01** [comment]
same i wait 1 minute and its not working
