### ISSUE TITLE
a bug that happens when you play a song with the play as opponent modifier

### ISSUE THREAD

**Issue by Gitgamer018** [Snirozu/Funkin-Psych-Online#63]
### Describe your bug here.

sometimes, out of nowhere, the game starts draining your health bar when you press a note instead of gaining health

### Steps to reproduce this bug.

it happens randommly

### Have you modded the build?

Yes, using Mods

### If you edited anything in this build, mention or summarize your changes.

i was playing this mod https://gamebanana.com/mods/495227

### What is your platform?

Windows

**Comment by NAEL2XD** [comment]
> ### Have you modded the build?
> Yes, using Mods

if a mod has a script that drains your health and you're on play as opponent mode, then that's normal. you'll have to disable that option (play as opponent)

**Comment by Gitgamer018** [comment]
theres not a single script in the mod related to health drain
