### ISSUE TITLE
Skin Bug

### ISSUE THREAD

**Issue by invert135** [Snirozu/Funkin-Psych-Online#66]
### Describe your bug here.

imported character files won't show up on psych online

### Steps to reproduce this bug.

insert it again

### Have you modded the build?

Yes, using Mods

### If you edited anything in this build, mention or summarize your changes.

nothing

### What is your platform?

Windows

**Comment by invert135** [comment]
mods path and yes

**Comment by kirito8803** [comment]
Do you still have the bug going on?
