### ISSUE TITLE
Issue compiling source

### ISSUE THREAD

**Issue by Spacefruuit** [Snirozu/Funkin-Psych-Online#67]
### Describe your bug here.

Code spits out a bunch of errors about variables being used before being initialized and missing linc_luajit 0.0.6 (Even though it should have been installed). Ive reset my computer after and tried running it again with the same issue

This could totally just be an issue with me missing something most people have installed that im just not aware of due to not frequently compiling

### Steps to reproduce this bug.

Fresh code copy, all thats been done has been cloning the repository, running hmm install, and running lime test windows

### Command Prompt/Terminal logs

```bash
E:/Friday Night Funkin/FNF Source Codes/Funkin-Psych-Online/.haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/io/colyseus/Client.hx:112: characters 28-34 : Warning : (WVarInit) Local variable onJoin might be used before being initialized
source/online/states/OnlineOptionsState.hx:123: characters 7-21 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:124: characters 7-21 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:129: characters 6-20 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:129: characters 38-52 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:130: characters 6-20 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:130: characters 38-52 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:132: characters 10-24 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:137: characters 10-24 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:138: characters 7-21 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:139: characters 7-21 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:144: characters 40-54 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:144: characters 71-85 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:146: characters 42-56 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/states/OnlineOptionsState.hx:146: characters 73-87 : Warning : (WVarInit) Local variable registerOption might be used before being initialized
source/online/substates/RoomSettingsSubstate.hx:94: characters 4-19 : Warning : (WVarInit) Local variable unlockModifiers might be used before being initialized
source/online/substates/RoomSettingsSubstate.hx:96: characters 4-19 : Warning : (WVarInit) Local variable unlockModifiers might be used before being initialized
source/online/substates/RoomSettingsSubstate.hx:106: characters 4-10 : Warning : (WVarInit) Local variable hideGF might be used before being initialized
source/online/substates/RoomSettingsSubstate.hx:108: characters 4-10 : Warning : (WVarInit) Local variable hideGF might be used before being initialized
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/linc_luajit/0,0,6/project/Build.xml"
```

### Have you modded the build?

Yes, at Source Code level

### If you edited anything in this build, mention or summarize your changes.

Have not touched anything, completely fresh build

### What is your platform?

Windows

**Comment by moxie-coder** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`

**Comment by Spacefruuit** [comment]
attempted that with no success same errors still this time with it not finding project/build.xml in the git version, second attempt in the screenshot was after installing it on another powershell terminal within C drive just case that made a difference
![Screenshot 2024-10-15 180450](https://github.com/user-attachments/assets/21e83808-11af-44b0-bc5a-efd8ea6b6879)
if the issue genuiinely is just that then uhh screw me i guess lmao but i also cant find that folder in the github repo or my own folder?? i guess if you have that file/folder sending it might help

**Comment by moxie-coder** [comment]
`haxelib --global git linc_luajit https://github.com/superpowers04/linc_luajit`

**Comment by Spacefruuit** [comment]
still no luck, same thing done. ran it in the current folder and on the terminal open to cdrive 

![Screenshot 2024-10-15 181543](https://github.com/user-attachments/assets/62a2d1ca-b6bd-4d8f-b458-08fc6ba6d62e)

**Comment by Spacefruuit** [comment]
fixed the issue, project folder was in the .haxelib folder in my cloned repo but it wasnt using that version of linc_luajit. coppied the folder to the location it was running it from and it worked
