### ISSUE TITLE
ChromeOS Linux Runtime error

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [Snirozu/Funkin-Psych-Online#72]
### Describe your bug here.

I'm probably stupid because of this happening, but here goes anyway because people here know what they're talking about.
I was using Android APK version previously because it just worked on chromeOS, but mods failed to download. so I'm trying this version now.

anyways, i don't use Linux, so I have no clue as to what the problem is

### Steps to reproduce this bug.

just try to load the Linux build through the Linux penguin terminal on chromeOS

### Command Prompt/Terminal logs

```bash
_chickenswimmer@penguin:~/FNF/PsychOnline$ sudo .PsychEngine
./PsychEngine: error while loading shared libraries: libvlc.so.5: cannot open shared object file: No such file or directory

(NOTE: if the sudo suffix isn't used, the terminal crashes instantly apon the error)
```

### Have you modded the build?

Yes, using Mods

### If you edited anything in this build, mention or summarize your changes.

(why is there no option for "no" under 'Have you modded the build?'??)

### What is your platform?

Linux

**Comment by Snirozu** [comment]
chromeos is not supported, but if you run on linux you can install the vlc package with `sudo apt-get install libvlc-dev` terminal command
